"""Set ondelete for chat graph_id

Revision ID: 0d0cb25ac2a7
Revises: b9912c262ba3
Create Date: 2025-09-24 10:34:01.627873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d0cb25ac2a7'
down_revision: Union[str, None] = 'b9912c262ba3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('chats_graph_id_fkey'), 'chats', type_='foreignkey')
    op.create_foreign_key(None, 'chats', 'graphs', ['graph_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chats', type_='foreignkey')
    op.create_foreign_key(op.f('chats_graph_id_fkey'), 'chats', 'graphs', ['graph_id'], ['id'])
    # ### end Alembic commands ###
