"""Initial migration

Revision ID: 3c2ccb978951
Revises: d3902c5f8f4a
Create Date: 2025-10-25 13:44:39.996808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c2ccb978951'
down_revision: Union[str, None] = 'd3902c5f8f4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('models_of_ai', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'models_of_ai', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'models_of_ai', type_='foreignkey')
    op.drop_column('models_of_ai', 'user_id')
    # ### end Alembic commands ###
