"""Initial migration

Revision ID: 5390542519ae
Revises: 8f1dae1459cf
Create Date: 2025-09-23 09:31:17.590479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5390542519ae'
down_revision: Union[str, None] = '8f1dae1459cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('graph_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'agents', 'graphs', ['graph_id'], ['id'])
    op.add_column('graphs', sa.Column('entry_node_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'graphs', 'nodes', ['entry_node_id'], ['id'])
    op.add_column('nodes', sa.Column('agent_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'nodes', 'agents', ['agent_id'], ['id'])
    op.drop_column('nodes', 'node_type')
    op.drop_column('nodes', 'name')
    op.drop_column('nodes', 'code_or_prompt')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nodes', sa.Column('code_or_prompt', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('nodes', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('nodes', sa.Column('node_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'nodes', type_='foreignkey')
    op.drop_column('nodes', 'agent_id')
    op.drop_constraint(None, 'graphs', type_='foreignkey')
    op.drop_column('graphs', 'entry_node_id')
    op.drop_constraint(None, 'agents', type_='foreignkey')
    op.drop_column('agents', 'graph_id')
    # ### end Alembic commands ###
