"""Initial migration

Revision ID: 6d3408b79075
Revises: 0d0cb25ac2a7
Create Date: 2025-09-26 09:47:27.881581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d3408b79075'
down_revision: Union[str, None] = '0d0cb25ac2a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('models_of_ai', sa.Column('api_key', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('models_of_ai', 'api_key')
    # ### end Alembic commands ###
