"""Initial migration

Revision ID: 85908bfc143d
Revises: 166c564b293b
Create Date: 2025-10-21 13:04:15.836718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85908bfc143d'
down_revision: Union[str, None] = '166c564b293b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_execution_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=True),
    sa.Column('graph_id', sa.Integer(), nullable=True),
    sa.Column('execution_timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('execution_path', sa.JSON(), nullable=True),
    sa.Column('node_outputs', sa.JSON(), nullable=True),
    sa.Column('manager_decisions', sa.JSON(), nullable=True),
    sa.Column('total_duration_ms', sa.Integer(), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ),
    sa.ForeignKeyConstraint(['graph_id'], ['graphs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('agent_execution_logs')
    # ### end Alembic commands ###
