"""Initial migration

Revision ID: 8d8e48d76c42
Revises: 3c2ccb978951
Create Date: 2025-10-25 13:48:51.291241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d8e48d76c42'
down_revision: Union[str, None] = '3c2ccb978951'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('agents_graph_id_fkey'), 'agents', type_='foreignkey')
    op.drop_column('agents', 'graph_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('graph_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('agents_graph_id_fkey'), 'agents', 'graphs', ['graph_id'], ['id'])
    # ### end Alembic commands ###
