"""Initial migration

Revision ID: 91186530df90
Revises: 8d8e48d76c42
Create Date: 2025-10-29 16:40:46.277930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91186530df90'
down_revision: Union[str, None] = '8d8e48d76c42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_model_link',
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['models_of_ai.id'], ),
    sa.PrimaryKeyConstraint('agent_id', 'model_id')
    )
    op.drop_constraint(op.f('agents_model_ai_id_fkey'), 'agents', type_='foreignkey')
    op.drop_column('agents', 'model_ai_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('model_ai_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('agents_model_ai_id_fkey'), 'agents', 'models_of_ai', ['model_ai_id'], ['id'])
    op.drop_table('agent_model_link')
    # ### end Alembic commands ###
