"""Initial migration

Revision ID: af0cf3b26d8f
Revises: 5390542519ae
Create Date: 2025-09-23 10:07:57.002735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af0cf3b26d8f'
down_revision: Union[str, None] = '5390542519ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('graph_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'chats', 'graphs', ['graph_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chats', type_='foreignkey')
    op.drop_column('chats', 'graph_id')
    # ### end Alembic commands ###
