"""Initial migration

Revision ID: b0be19d2b65c
Revises: 34d5e1717e8e
Create Date: 2025-09-22 18:38:29.896586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0be19d2b65c'
down_revision: Union[str, None] = '34d5e1717e8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'agents', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'agents', type_='foreignkey')
    op.drop_column('agents', 'user_id')
    # ### end Alembic commands ###
