"""Initial migration

Revision ID: cec0f44a5e9c
Revises: 6d3408b79075
Create Date: 2025-09-28 20:14:29.605643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cec0f44a5e9c'
down_revision: Union[str, None] = '6d3408b79075'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('description', sa.String(length=100), nullable=True))
    op.add_column('agents', sa.Column('tools', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'tools')
    op.drop_column('agents', 'description')
    # ### end Alembic commands ###
