"""Initial migration

Revision ID: d3902c5f8f4a
Revises: 85908bfc143d
Create Date: 2025-10-22 18:22:56.468739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3902c5f8f4a'
down_revision: Union[str, None] = '85908bfc143d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('graph_execution_logs', sa.Column('audit_trail', sa.JSON(), nullable=True))
    op.add_column('graph_execution_logs', sa.Column('flow_steps', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('graph_execution_logs', 'flow_steps')
    op.drop_column('graph_execution_logs', 'audit_trail')
    # ### end Alembic commands ###
